version: '3.2'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./nextcloud_volume/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user

  app:
    build: nextcloud
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./nextcloud_volume/data:/var/www/nextcloud/data
      - ./nextcloud_volume/config:/var/www/nextcloud/config
    environment:
      - DATADIRECTORY=/var/www/nextcloud/data
      - FILESYSTEM_CHECK_CHANGES=1
      - POSTGRES_HOST=db:5432
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
      - NEXTCLOUD_TRUSTED_DOMAINS=localhost
    depends_on:
      - db
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - postgres_db
      - postgres_password
      - postgres_user
      - minio_user
      - minio_password


secrets:
  nextcloud_admin_password:
    file: ./nextcloud_admin_password.txt # put admin password to this file
  nextcloud_admin_user:
    file: ./nextcloud_admin_user.txt # put admin username to this file
  postgres_db:
    file: ./postgres_db.txt # put postgresql db name to this file
  postgres_password:
    file: ./postgres_password.txt # put postgresql password to this file
  postgres_user:
    file: ./postgres_user.txt # put postgresql username to this file
  minio_user:
    file: ./minio_user.txt
  minio_password:
    file: ./minio_password.txt


